"""
应用常量：审计操作类型、业务文案等，便于维护与统一引用。
"""

# 审计日志操作类型（与 models.AuditLog.action_type 一致）
AUDIT_LOGIN = "LOGIN"
AUDIT_QUERY_SINGLE = "QUERY_SINGLE"
AUDIT_QUERY_BATCH = "QUERY_BATCH"
AUDIT_IMPORT = "IMPORT"
AUDIT_ADD = "ADD"
AUDIT_DELETE = "DELETE"
AUDIT_RESTORE = "RESTORE"
AUDIT_BACKUP = "BACKUP"

# 审计类型列表（用于筛选等）
AUDIT_ACTION_TYPES = [
    AUDIT_LOGIN,
    AUDIT_QUERY_SINGLE,
    AUDIT_QUERY_BATCH,
    AUDIT_IMPORT,
    AUDIT_ADD,
    AUDIT_DELETE,
    AUDIT_RESTORE,
    AUDIT_BACKUP,
]

# 名单状态
BLACKLIST_STATUS_EFFECTIVE = 1
BLACKLIST_STATUS_REVOKED = 0
